### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by mirfan899** [grammatical/neural-naacl2018#13]
I tried to follow the training documentation. When I run the 
```shell
cd data
make all
cd ..
```
It gives the following error.

```shell
python ../tools/spellcheck.py < ../tools/jfleg/dev/dev.src > jflegdev.err
Traceback (most recent call last):
  File "../tools/spellcheck.py", line 30, in <module>
    main()
  File "../tools/spellcheck.py", line 19, in main
    print(d.suggest(w)[0], end=" ")
IndexError: list index out of range
make: *** [Makefile:54: jflegdev.err] Error 1
make: *** Deleting file 'jflegdev.err'
```
I have the file `dev.src` in `tools/jfleg/dev/`

I'm using Python 2 for this experiment as it seems it does not support Python 3.

**Comment by mirfan899** [comment]
It seems this is a bug in `spellcheck.py` code. For example, there is a line in `dev.src` 
```text
the carebendiocside is very harm full for the people . 
```
enchant gives an empty array for word `carebendiocside` and the script throws the error.

**Comment by mirfan899** [comment]
Here is the fix I am using

```python
def main():
    args = parse_user_args()
    d = enchant.Dict(args.dict)
    for line in sys.stdin:
        for w in line.strip().split():
            if d.check(w) or not w.isalpha():
                print(w, end=" ")
            elif d.suggest(w):
                print(d.suggest(w)[0], end=" ")
        print()
```

`else` case can be built. I don't know the logic and context of the script so I'm not using it.
