### ISSUE TITLE
Error evaluating test datasets

### ISSUE THREAD

**Issue by gcunhase** [grammatical/neural-naacl2018#7]
I'm trying to evaluate the test datasets on the pre-trained models as instructed in *models/README.md*.

However, when running `bash evaluate.sh 0`, I get an *AssertionError* saying that *candidates*, *sources* and *gold_edits* have different lengths. I found out that JFLEG works well but not CoNLL 2013 and 2014.

Anyone have any advice? I'm currently using CUDA 9.0, Python 3.6 and PyTorch 0.4.0. Here is the error I currently have:
```
CoNLL Test 2013
Traceback (most recent call last):
  File "./tools/remove_repetitions.py", line 62, in <module>
    main()
  File "./tools/remove_repetitions.py", line 16, in main
    ngrams = get_ngrams(words, args.max_size, args.min_freq)
  File "./tools/remove_repetitions.py", line 47, in get_ngrams
    for ngram in counts.keys():
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "/mnt/gwena/Gwena/IncompleteIntentionClassifier/baseline/gec_models/neural-naacl2018/models/tools/subword-nmt/subword_nmt/apply_bpe.py", line 373, in <module>
    args.output.write(bpe.process_line(line))
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "./tools/m2scorer/scripts/m2scorer.py", line 137, in <module>
    p, r, f1 = levenshtein.batch_multi_pre_rec_f1(system_sentences, source_sentences, gold_edits, max_unchanged_words, beta, ignore_whitespace_casing, verbose, very_verbose)
  File "/mnt/gwena/Gwena/IncompleteIntentionClassifier/baseline/gec_models/neural-naacl2018/models/tools/m2scorer/scripts/levenshtein.py", line 107, in batch_multi_pre_rec_f1
    assert len(candidates) == len(sources) == len(gold_edits)
AssertionError
```

**Comment by snukky** [comment]
It seems that `remove_repetitions.py` is not compatible with Python 3.x and your `python` command runs Python 3.6. If you have `python2` available you may explicitly use it in this line: https://github.com/grammatical/neural-naacl2018/blob/master/models/evaluate.sh#L32
You may also try removing `remove_repetitions.py` form the pipeline. This should not change the results significantly.

**Comment by gcunhase** [comment]
Thank you for your reply @snukky! I tried removing `remove_repetitions.py` from the pipeline and also downgrading my Python version to 2.7, but I still get the same error...

EDIT: FIXED! After downgrading, I reinstalled everything in *./tools* and it works! Thank you!

**Comment by snukky** [comment]
Fixed in the last commit.
